---
name: CI

on:
  push:
    branches: [ main ]


jobs:
  FunctionTest:
    name: Function Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Go to the directory
        run: cd ./func-dojo-cicd-skool

      - name: npm install
        run: npm install

      - name: npm test:coverage
        run: npm run test:coverage

      - name: Move reports directory
        run: |
          cd ../
          mkdir -p reports/jest
          mv ./func-dojo-cicd-skool/coverage ./reports/jest/coverage

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage
          path: ./reports/jest/coverage