---
name: CI

on: push

jobs:
  FunctionTest:
    name: Function Test
    runs-on: ubuntu-latest
    env:
      workdir: func-dojo-cicd-skool
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: npm install
        working-directory: ${{ env.workdir }}
        run: npm install

      - name: npm test:coverage
        working-directory: ${{ env.workdir }}
        run: npm run test:coverage

      - name: Move reports directory
        run: |
          mkdir -p reports/jest
          mv ./func-dojo-cicd-skool/coverage ./reports/jest/coverage

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: jest-coverage
          path: ./reports/jest/coverage